# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v20.11.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2024-02-13
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 20.11.1
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v20.11.1/node-v20.11.1-x86.msi
  InstallerSha256: 63E2AED4DABB96EED6903A3974E006D3C29C218472AAC60AE3C3C7DE00DF13B1
  ProductCode: '{5F30578D-F954-47F8-B6A3-E50A053F78BE}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi
  InstallerSha256: C54F5F7E2416E826FD84E878F28E3B53363AE9C3F60A140AF4434B2453B5AE89
  ProductCode: '{DA5C7599-681B-43F8-B8A6-20D986C704F9}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi
  InstallerSha256: C54F5F7E2416E826FD84E878F28E3B53363AE9C3F60A140AF4434B2453B5AE89
  ProductCode: '{DA5C7599-681B-43F8-B8A6-20D986C704F9}'
ManifestType: installer
ManifestVersion: 1.6.0
