# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 10.17.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2019-10-22
AppsAndFeaturesEntries:
- DisplayName: Node.js
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v10.17.0/node-v10.17.0-x86.msi
  InstallerSha256: 2281CEACE216BBCE7FA0A5ECE8EB8650B961BBF03019400B3DF5481BA3CD20B1
  ProductCode: '{9A3F4E8A-0D91-4ECE-868B-9C776371201D}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v10.17.0/node-v10.17.0-x64.msi
  InstallerSha256: 259A6A29B6F39685E0752E5F5153EBC6F4146AEFD27FF18E8C1605D0826597FE
  ProductCode: '{13BC146A-9F0B-47F6-96CD-3458EB4D3490}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v10.17.0/node-v10.17.0-x64.msi
  InstallerSha256: 259A6A29B6F39685E0752E5F5153EBC6F4146AEFD27FF18E8C1605D0826597FE
  ProductCode: '{13BC146A-9F0B-47F6-96CD-3458EB4D3490}'
ManifestType: installer
ManifestVersion: 1.6.0
