# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v14.17.5
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2021-08-11
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 14.17.5
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v14.17.5/node-v14.17.5-x86.msi
  InstallerSha256: 53763A06FF498D9DEABFF2CC6F4041D0A3C3F38F940ACB6C8A8339DF8D8B3827
  ProductCode: '{D399F6F1-70F7-42C7-B40F-347BD2EB8E3F}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v14.17.5/node-v14.17.5-x64.msi
  InstallerSha256: F40926F33C4517A64978050FB8E88110D279A3A15ADC962DE4002F65ED34E821
  ProductCode: '{BBA8BA33-A3FC-47F3-A144-B95FB83B4FB4}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v14.17.5/node-v14.17.5-x86.msi
  InstallerSha256: 53763A06FF498D9DEABFF2CC6F4041D0A3C3F38F940ACB6C8A8339DF8D8B3827
  ProductCode: '{D399F6F1-70F7-42C7-B40F-347BD2EB8E3F}'
ManifestType: installer
ManifestVersion: 1.6.0
