# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 6.16.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2018-12-26
AppsAndFeaturesEntries:
- DisplayName: Node.js
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.16.0/node-v6.16.0-x86.msi
  InstallerSha256: 5E2424B372A40DB42775E747A98E11979BC0DFC7BD3D1D87A49F9E19F087BF93
  ProductCode: '{3F5AE5C5-6089-4B13-ACA3-4DEFC36A3737}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.16.0/node-v6.16.0-x64.msi
  InstallerSha256: CD58A0467828C34A59AA0AB8D10099CF928CB30ADCF313BDA8EC08939E91E56A
  ProductCode: '{7CEE5A0D-2664-48CC-AB02-7F2F918C5305}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.16.0/node-v6.16.0-x86.msi
  InstallerSha256: 5E2424B372A40DB42775E747A98E11979BC0DFC7BD3D1D87A49F9E19F087BF93
  ProductCode: '{3F5AE5C5-6089-4B13-ACA3-4DEFC36A3737}'
ManifestType: installer
ManifestVersion: 1.6.0
