# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v6.17.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2019-04-03
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 6.17.1
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.17.1/node-v6.17.1-x86.msi
  InstallerSha256: DB11F92D99E1B2289BF62F6CB8E9173FEA680C0371D74DE0F61802519DC07613
  ProductCode: '{CEF9002F-C8A4-4CF2-9BAA-E50D88369FC4}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.17.1/node-v6.17.1-x64.msi
  InstallerSha256: E3A3816D7184EB90162B0FC7B0F2B7F6F2BA5C11C4C6D8DC1BD8B7DA40A7C514
  ProductCode: '{5D44C1AC-E450-48DB-A06E-D5CB84F8BDD9}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.17.1/node-v6.17.1-x64.msi
  InstallerSha256: E3A3816D7184EB90162B0FC7B0F2B7F6F2BA5C11C4C6D8DC1BD8B7DA40A7C514
  ProductCode: '{5D44C1AC-E450-48DB-A06E-D5CB84F8BDD9}'
ManifestType: installer
ManifestVersion: 1.6.0
