# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: DenoLand.Deno
PackageVersion: 1.41.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles: []
ReleaseDate: 2024-02-22
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/denoland/deno/releases/download/v1.41.0/denort-x86_64-pc-windows-msvc.zip
  InstallerSha256: CF624683DCB678C7EB9A612D20787AAD25FB9F3F431D976BABFF93BB4BE3D4B9
ManifestType: installer
ManifestVersion: 1.6.0
