# Created with komac v2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 10.15.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2018-12-26
AppsAndFeaturesEntries:
- DisplayName: Node.js
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v10.15.0/node-v10.15.0-x86.msi
  InstallerSha256: 9B4B01C5E8181CAA2B48DED5B481773B504B54B6145754A09AAE8DE948E46053
  ProductCode: '{6C949342-38E6-4688-9B44-EA39E875751F}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v10.15.0/node-v10.15.0-x64.msi
  InstallerSha256: 1CF90EA486607A1E4E3191E4880D4E6A256168D800FE33A6E46680149B88E3ED
  ProductCode: '{7E005925-0125-4A46-8B25-6DB1547488C2}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v10.15.0/node-v10.15.0-x86.msi
  InstallerSha256: 9B4B01C5E8181CAA2B48DED5B481773B504B54B6145754A09AAE8DE948E46053
  ProductCode: '{6C949342-38E6-4688-9B44-EA39E875751F}'
ManifestType: installer
ManifestVersion: 1.6.0
