# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v10.20.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2020-04-12
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 10.20.1
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v10.20.1/node-v10.20.1-x86.msi
  InstallerSha256: 61891D726A57C6DFDF1B78D1F73563DC02BB1EDD4227E811FD4821FA0412341C
  ProductCode: '{E7EE1956-9256-43BD-9BF9-BFA04482DD6B}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v10.20.1/node-v10.20.1-x64.msi
  InstallerSha256: 3BFC5EF20F4E93EC5BFB910C301101880D429409CD23E8F793618BF3CAA5112B
  ProductCode: '{EE7280CD-5EFF-4831-8C78-F98C241CFBAF}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v10.20.1/node-v10.20.1-x86.msi
  InstallerSha256: 61891D726A57C6DFDF1B78D1F73563DC02BB1EDD4227E811FD4821FA0412341C
  ProductCode: '{E7EE1956-9256-43BD-9BF9-BFA04482DD6B}'
ManifestType: installer
ManifestVersion: 1.6.0
