# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v4.8.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2017-02-21
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 4.8.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v4.8.0/node-v4.8.0-x86.msi
  InstallerSha256: F6AF223F732953981B94D576F492F59C168713D7C1148FC512E42E1DADD9B5E0
  ProductCode: '{7EEB63EC-0270-4853-AC86-F39B0ED0991C}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v4.8.0/node-v4.8.0-x64.msi
  InstallerSha256: 07A44C3289F5FE8082388928B9511A75106392D01B10CC24B5A19E376912D264
  ProductCode: '{5DD3AD85-FB77-485D-8EB6-BD2BFF017061}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v4.8.0/node-v4.8.0-x64.msi
  InstallerSha256: 07A44C3289F5FE8082388928B9511A75106392D01B10CC24B5A19E376912D264
  ProductCode: '{5DD3AD85-FB77-485D-8EB6-BD2BFF017061}'
ManifestType: installer
ManifestVersion: 1.6.0
