# Created with Komac v1.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Microsoft.PowerToys
PackageVersion: 0.78.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://github.com/microsoft/PowerToys
PublisherSupportUrl: https://github.com/microsoft/PowerToys/issues
PrivacyUrl: https://privacy.microsoft.com/en-us/privacystatement
Author: Microsoft Corporation
PackageName: PowerToys (Preview)
PackageUrl: https://github.com/microsoft/PowerToys
License: MIT
LicenseUrl: https://github.com/microsoft/PowerToys/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
CopyrightUrl: https://github.com/microsoft/PowerToys/blob/main/LICENSE
ShortDescription: Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows experience for greater productivity.
Description: |-
  Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows experience for greater productivity.
  Inspired by the Windows 95 era PowerToys project, this reboot provides power users with ways to squeeze more efficiency out of the Windows 10 shell and customize it for individual workflows.
Moniker: powertoys
Tags:
- colorpicker
- fancyzones
- fileexplorer
- imageresizer
- keyboardmanager
- power-toys
- powerrename
- powertoys
- powertoys-run
- windows-key-shortcut-guide
ReleaseNotes: |-
  Highlights
  - New languages added: Arabic (Saudi Arabia), Hebrew, Persian and Ukrainian.
    We are going to assume we have some bugs.
    We want to identify & fix them and are open for community help.
  - Many dependencies updated, aiming for security and stability.
  - Fixed commonly reported PowerToys Run startup crashes after an upgrade.
  - New settings and GPO policies to help control behavior after an upgrade.
    Thanks @htcfreek!
  General
  - Added Arabic (Saudi Arabia) translation.
  - Added Hebrew translation.
  - Added Persian translation.
  - Added Ukrainian translation.
  - Improved the file watcher used across many utilities to consume less resources.
    Thanks @davidegiacometti!
  AlwaysOnTop
  - Fixed an invisible border issue when the border color was set to the black color.
  - Added the AlwayOnTop icon to the base application executable.
    Thanks @ckirby19!
  Command Not Found
  - Signed the PowerShell scripts used by the Command Not Found installation process.
  File Explorer add-ons
  - Fixed an issue causing SVG Thumbnail generation to hang when trying to preview SVG files at the same time.
  File Locksmith
  - Improved the context menu entry caption.
    Thanks @niels9001!
  Find My Mouse
  - Added more settings to tune shake detection when activating through mouse shake.
  Hosts File Editor
  - Added a feature to duplicate an entry.
    Thanks @davidegiacometti!
  Installer
  - Included the new languages localization files in the installer.
  Image Resizer
  - Improved the context menu entry caption.
    Thanks @niels9001!
  Peek
  - Added a missing tooltip for the file size.
    Thanks @HydroH!
  PowerRename
  - Improved and added localization to the context menu entry caption.
    Thanks @niels9001!
  PowerToys Run
  - Removed references to unused settings from the code, which were causing crashes on some machines.
    Thanks @davidegiacometti!
  - Fixed an issue causing a scrollbar to be out of view.
    Thanks @niels9001!
  - Added logic to try and detect running games to full screen detection.
    Thanks @anaisbetts!
  - Added support for converting negative values in the Unit Converter plugin.
    Thanks @Dub1shu!
  - Fixed stale results in the Visual Studio Code Workspaces plugin by checking if files still exist.
    Thanks @anderspk!
  - Fixed an activation crash that occurred after 0.77 on some configurations.
  - Fixed a startup crash that occurred when saving the new version of settings after an upgrade.
  - You can now calculate bigger hexadecimal numbers in the Calculator plugin.
  - The "max results to show before scrolling" setting can now also be applied to the initial plugin hint listing.
  Quick Accent
  - Added the ellipses character to all languages.
    Thanks @HydroH!
  - Added an option to not activate when playing a game.
    Thanks @HydroH!
  - Added the E with breve and pilcrow characters to all languages.
    Thanks @PesBandi!
  Settings
  - Removed the Command Not Found listing from the Settings dashboard and flyout, since it can't really be enabled or disabled from there.
  - Added a settings and GPO rule to disable opening the What's New OOBE page after an update.
    Thanks @htcfreek!
  - Added a settings and GPO rule to disable toast notifications about new updates being available.
    Thanks @htcfreek!
  - Fixed an issue causing the Settings window to not be brought to the foreground after activating through the system tray icon.
  - Standardized accent brush and corner radius on the dashboard page.
  - Improved UI and messages for GPO locked settings.
    Thanks @htcfreek!
  - Fixed an issue causing the OOBE window to maximize and hide the system taskbar.
  - Reworked the update settings in the General page.
    Thanks @htcfreek!
  - Tweaked UI for the update settings in the General page.
    Thanks @niels9001!
  - Updated the modules images in the Settings and OOBE screens.
    Thanks @niels9001!
  - Updated OOBE descriptions to take into account the changes in context menu captions.
    Thanks @niels9001!
  Documentation
  - Added Spotify plugin to PowerToys Run thirdPartyRunPlugins.md docs.
    Thanks @waaverecords!
  - Added InputTyper and ClipboardManager plugins to PowerToys Run thirdPartyRunPlugins.md docs.
    Thanks @CoreyHayward!
  - Added CurrencyConverter plugin to PowerToys Run thirdPartyRunPlugins.md docs.
    Thanks @Advaith3600!
  - Updated and cleaned up the new PowerToys plugin checklist documentation.
    Thanks @Parvezkhan0 and @hlaueriksson!
  - Added a documentation page to describe status code colors for Mouse Without Borders.
    Thanks @ckirby19!
  Development
  - Fixed dependency issues on upgrading .
    NET from 8.0.0 to 8.0.1.
  - Upgraded Microsoft.
    Extensions.
    ObjectPool from .
    NET 5 to .NET 8.
  - Upgraded the Windows SDK Build Tools to 10.0.22621.2428.
  - Upgraded the Windows Implementation Library to 1.0.231216.1.
  - Upgraded NLog.
    Schema to 5.2.8 and NLog.
    Extensions.
    Logging to 5.3.8.
  - Upgraded Markdig.
    Signed to 0.34.0.
  - Upgraded Microsoft.
    NET.Test.
    Sdk to 17.8.
  - Upgraded CommunityToolkit.
    WinUI dependencies to 8.0.240109.
  - Upgraded CommunityToolkit.
    Mvvm to 8.2.2.
    Thanks @davidegiacometti!
  - Upgraded Windows App SDK to 1.4.4.
    Thanks @snickler!
  - Upgraded WPFUI version to 3.0.0-preview.13.
    Thanks @niels9001!
  - Upgraded StyleCop.
    Analyzers to 1.2.0-beta.556.
    Thanks @davidegiacometti!
  - Upgraded Microsoft.
    Windows.
    Compatibility to 8.0.1.
  - Upgraded System.
    Data.
    SqlClient to 4.8.6.
  - Consolidate XAML Namespaces across the solutions.
    Thanks @Jay-o-Way!
  - Removed the toolkit labs package source reference, since the controls we were using made it to the generally available community toolkit.
  - Added Microsoft.
    MSBuildCache to experiment with build caching to reduce pipeline runs duration.
    Thanks @dfederm!
  - Configured the release CI to follow the latest 1ES pipeline release version again.
  - Removed the copyright year from assembly information.
    Thanks @Aaron-Junker!
  - Added the Command Not Found entry to the GitHub templates.
  - Removed unused code for a GPO policy to control auto updating of PowerToys.
    Thanks @htcfreek!
  - Improved code behind for getting the localization of context menu entries.
  - Locked some terms in resource files to avoid localization.
ReleaseNotesUrl: https://github.com/microsoft/PowerToys/releases/tag/v0.78.0
ManifestType: defaultLocale
ManifestVersion: 1.5.0
