# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v6.10.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2017-02-22
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 6.10.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.10.0/node-v6.10.0-x86.msi
  InstallerSha256: 65ADD5AEBB209705DACC8462A5376DCB612E19B3F2AF1CE1E8A0C7E1C95E3E81
  ProductCode: '{159D3B59-62F3-4C12-8D83-E1162B077033}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.10.0/node-v6.10.0-x64.msi
  InstallerSha256: 0FD99472EDD0EF518AC557C24C037F83F4C82341348A2B397D51410550B6217C
  ProductCode: '{84F68739-3B44-4D36-ABDB-2151A23C9C3D}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.10.0/node-v6.10.0-x86.msi
  InstallerSha256: 65ADD5AEBB209705DACC8462A5376DCB612E19B3F2AF1CE1E8A0C7E1C95E3E81
  ProductCode: '{159D3B59-62F3-4C12-8D83-E1162B077033}'
ManifestType: installer
ManifestVersion: 1.6.0
