# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v12.17.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2020-05-26
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 12.17.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v12.17.0/node-v12.17.0-x86.msi
  InstallerSha256: 9BCF24B14C84799EE48B9A9E6BB83058E434FBB1A61D9FB59918A0C296164D26
  ProductCode: '{F6D3BA33-B50C-4CCE-96FF-2A75C00AABC8}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v12.17.0/node-v12.17.0-x64.msi
  InstallerSha256: FCF7ABAAFD5DEDE76104527D064F88EC1F2D2131DC9A0F5387FE2C0ABBD1BA94
  ProductCode: '{D2C4D28A-EB22-44BA-866C-AB471A167539}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v12.17.0/node-v12.17.0-x86.msi
  InstallerSha256: 9BCF24B14C84799EE48B9A9E6BB83058E434FBB1A61D9FB59918A0C296164D26
  ProductCode: '{F6D3BA33-B50C-4CCE-96FF-2A75C00AABC8}'
ManifestType: installer
ManifestVersion: 1.6.0
