# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v6.9.5
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2017-01-31
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 6.9.5
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.9.5/node-v6.9.5-x86.msi
  InstallerSha256: FF6C7033B51E8C3DD64A0E71D37738C0F96A4388A3F310151B172B028460776F
  ProductCode: '{B505A390-3E55-4967-BA46-8A958070DBF4}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.9.5/node-v6.9.5-x64.msi
  InstallerSha256: CFCC1F41907F40FFCCEBB24A409283853926DDF7B2B3D026DB0EDB40ED98D2FF
  ProductCode: '{4F1DFC88-F671-4DD8-9DE1-36CDB5A4B9B8}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.9.5/node-v6.9.5-x86.msi
  InstallerSha256: FF6C7033B51E8C3DD64A0E71D37738C0F96A4388A3F310151B172B028460776F
  ProductCode: '{B505A390-3E55-4967-BA46-8A958070DBF4}'
ManifestType: installer
ManifestVersion: 1.6.0
