# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v6.15.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2018-12-03
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 6.15.1
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.15.1/node-v6.15.1-x86.msi
  InstallerSha256: 7C085E59EBDD8FC9A2090B3C68765ACC2314E8FCE347F468F67E70420E238A3A
  ProductCode: '{D513DF46-008E-46FC-86D0-B950EB2424C0}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.15.1/node-v6.15.1-x64.msi
  InstallerSha256: 9FDA93A5AD0FC2B5EF8BDDCAE697365B4FFCE6A366814D4ADF22ED813F189D8D
  ProductCode: '{8AA4E5A3-8136-4FBF-96D6-62724ED9B614}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.15.1/node-v6.15.1-x64.msi
  InstallerSha256: 9FDA93A5AD0FC2B5EF8BDDCAE697365B4FFCE6A366814D4ADF22ED813F189D8D
  ProductCode: '{8AA4E5A3-8136-4FBF-96D6-62724ED9B614}'
ManifestType: installer
ManifestVersion: 1.6.0
