# Created with AutoPublish using komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: 7zip.7zip
PackageVersion: '24.07'
InstallerType: exe
Scope: machine
UpgradeBehavior: install
Commands:
- 7z
FileExtensions:
- '001'
- 7z
- apfs
- arj
- bz2
- bzip2
- cab
- cpio
- deb
- dmg
- esd
- fat
- gz
- gzip
- hfs
- iso
- lha
- lzh
- lzma
- ntfs
- rar
- rpm
- squashfs
- swm
- tar
- taz
- tbz
- tbz2
- tgz
- tpz
- txz
- tzst
- vhd
- vhdx
- wim
- xar
- xz
- z
- zip
- zst
ReleaseDate: 2024-06-19
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://7-zip.org/a/7z2407.exe
  InstallerSha256: 151261D221BA0F6120C7F16700AB0724B92FF3230F05A89EF15DBCD8198678BB
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
- Architecture: x86
  InstallerUrl: https://7-zip.org/a/7z2407.exe
  InstallerSha256: 151261D221BA0F6120C7F16700AB0724B92FF3230F05A89EF15DBCD8198678BB
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
    InstallLocation: /D="<INSTALLPATH>"
- Architecture: x64
  InstallerUrl: https://7-zip.org/a/7z2407-x64.exe
  InstallerSha256: AD12CEC3A3957FF73A689E0D65A05B6328C80FD76336A1B1A6285335F8DAB1BA
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
    InstallLocation: /D="<INSTALLPATH>"
- Architecture: x64
  InstallerUrl: https://7-zip.org/a/7z2407.exe
  InstallerSha256: 151261D221BA0F6120C7F16700AB0724B92FF3230F05A89EF15DBCD8198678BB
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
- Architecture: arm
  InstallerUrl: https://7-zip.org/a/7z2407.exe
  InstallerSha256: 151261D221BA0F6120C7F16700AB0724B92FF3230F05A89EF15DBCD8198678BB
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
    InstallLocation: /D="<INSTALLPATH>"
- Architecture: arm64
  InstallerUrl: https://7-zip.org/a/7z2407-arm64.exe
  InstallerSha256: FFD49DA0CA77D5376D9040D6CCD3A9963F6355F3E796455812569B4C61593F34
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
    InstallLocation: /D="<INSTALLPATH>"
ManifestType: installer
ManifestVersion: 1.6.0
