# Created with AutoPublish using komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: 7zip.7zip
PackageVersion: '24.07'
PackageLocale: en-US
Publisher: Igor Pavlov
PublisherUrl: https://7-zip.org/
PublisherSupportUrl: https://7-zip.org/support.html
Author: Igor Pavlov
PackageName: 7-Zip
PackageUrl: https://7-zip.org/
License: LGPL-2.1
LicenseUrl: https://7-zip.org/license.txt
Copyright: Copyright (C) 1999-2024 Igor Pavlov.
ShortDescription: 7-Zip is a file archiver with a high compression ratio.
Moniker: 7zip
Tags:
- archive
- archiver
- compress
- compression
- decompress
- decompression
- extract
- extractor
- unachive
- unachiver
- unzip
- zip
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://7-zip.org/faq.html
ManifestType: defaultLocale
ManifestVersion: 1.6.0
