# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v16.14.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2022-03-16
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 16.14.1
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v16.14.1/node-v16.14.1-x86.msi
  InstallerSha256: D9056D91A98A89D94C6F467113845C0BB88C2483F561A345D0817873D4207D45
  ProductCode: '{F927E173-8D39-4C15-9FBC-2F051EEA1044}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v16.14.1/node-v16.14.1-x64.msi
  InstallerSha256: E14FEBF43B622C963B4D149057C4252548AB0807FB3D90F8734AB0A092B9A2B7
  ProductCode: '{A4B6B49F-7232-4010-8233-5BE6A97C5EF4}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v16.14.1/node-v16.14.1-x64.msi
  InstallerSha256: E14FEBF43B622C963B4D149057C4252548AB0807FB3D90F8734AB0A092B9A2B7
  ProductCode: '{A4B6B49F-7232-4010-8233-5BE6A97C5EF4}'
ManifestType: installer
ManifestVersion: 1.6.0
