# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v6.13.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2018-02-13
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 6.13.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.13.0/node-v6.13.0-x86.msi
  InstallerSha256: 9994209ED23369E99D2FA38F790F0854C9EA8EB7755C703443357B1DD68CCAF1
  ProductCode: '{AE8547D5-4512-4D31-BD3C-85EAF2E7D38A}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.13.0/node-v6.13.0-x64.msi
  InstallerSha256: DF43AFCF21373F766140393C9E6285ABFBE058A91A54714391B0E0B1F7E0DDA9
  ProductCode: '{2E9C84D7-614F-4404-A298-B088A8FE4BC3}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.13.0/node-v6.13.0-x86.msi
  InstallerSha256: 9994209ED23369E99D2FA38F790F0854C9EA8EB7755C703443357B1DD68CCAF1
  ProductCode: '{AE8547D5-4512-4D31-BD3C-85EAF2E7D38A}'
ManifestType: installer
ManifestVersion: 1.6.0
