# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v12.18.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2020-06-17
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 12.18.1
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v12.18.1/node-v12.18.1-x86.msi
  InstallerSha256: F4A2FC3406E9208B3F8BE30C7AE46427D76FCEA18CF878368CA7A8FA47DC7EA6
  ProductCode: '{6A940540-DD4F-40B9-AC0E-26DB41FDD8A1}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v12.18.1/node-v12.18.1-x64.msi
  InstallerSha256: F318BB719BD956D4734247C58B3937DAEF04A01DBEE4ABDFE6217BDEA87932F4
  ProductCode: '{36AAFE4E-38A2-4721-86FC-4A700EEFDE08}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v12.18.1/node-v12.18.1-x64.msi
  InstallerSha256: F318BB719BD956D4734247C58B3937DAEF04A01DBEE4ABDFE6217BDEA87932F4
  ProductCode: '{36AAFE4E-38A2-4721-86FC-4A700EEFDE08}'
ManifestType: installer
ManifestVersion: 1.6.0
