# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v16.18.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2022-10-12
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 16.18.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v16.18.0/node-v16.18.0-x86.msi
  InstallerSha256: D80BE5BB62D00FB68B7158DA44FB1E4AF829223ED526C8F33DB3F29D5E47DB2D
  ProductCode: '{D45AF3A2-33EE-49B1-A575-80C922C1CE7C}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v16.18.0/node-v16.18.0-x64.msi
  InstallerSha256: C9D61A2E78BD836B02CBA87ADEBCB043AA27D1A8E4B2FDA0BA604AD180EB50BF
  ProductCode: '{4317906F-88C3-4031-924E-8456B4CB385F}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v16.18.0/node-v16.18.0-x64.msi
  InstallerSha256: C9D61A2E78BD836B02CBA87ADEBCB043AA27D1A8E4B2FDA0BA604AD180EB50BF
  ProductCode: '{4317906F-88C3-4031-924E-8456B4CB385F}'
ManifestType: installer
ManifestVersion: 1.6.0
