# Created with AutoPublish using komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Genymobile.scrcpy
PackageVersion: '2.5'
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2024-06-29
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: scrcpy-win32-v2.5/scrcpy.exe
    PortableCommandAlias: scrcpy
  InstallerUrl: https://github.com/Genymobile/scrcpy/releases/download/v2.5/scrcpy-win32-v2.5.zip
  InstallerSha256: D56312A92471565FA4F3A6B94E8EB07717C4C90F2C0F05B03BA444E1001806EC
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: scrcpy-win64-v2.5/scrcpy.exe
    PortableCommandAlias: scrcpy
  InstallerUrl: https://github.com/Genymobile/scrcpy/releases/download/v2.5/scrcpy-win64-v2.5.zip
  InstallerSha256: 345CF04A66A9144281DCE72CA4E82ADFD2C3092463196E586051DF4C69E1507B
ManifestType: installer
ManifestVersion: 1.6.0
