# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v12.18.4
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2020-09-15
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 12.18.4
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v12.18.4/node-v12.18.4-x86.msi
  InstallerSha256: 8E7E5D605704A1701FE096825792AE9E98946E5D99FC7F022AA9981DA57693C4
  ProductCode: '{303B9F6E-2D70-4859-A6ED-929987E4288B}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v12.18.4/node-v12.18.4-x64.msi
  InstallerSha256: 4BB3AEBCC2D22191C2DAAF4E419E923D891331F86A64CCA468F689E7A12A7E3C
  ProductCode: '{FF16978A-7B91-4098-98F5-BB080AEEABFE}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v12.18.4/node-v12.18.4-x86.msi
  InstallerSha256: 8E7E5D605704A1701FE096825792AE9E98946E5D99FC7F022AA9981DA57693C4
  ProductCode: '{303B9F6E-2D70-4859-A6ED-929987E4288B}'
ManifestType: installer
ManifestVersion: 1.6.0
