# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 6.9.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2016-10-19
AppsAndFeaturesEntries:
- DisplayName: Node.js
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v6.9.1/node-v6.9.1-x86.msi
  InstallerSha256: 314EAF8B5B9E08A835CB5C005EA5F4299B9E9E4D8C97277C1617E511382C15DC
  ProductCode: '{CA6817E2-FC84-4443-A2AE-FC244047E898}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v6.9.1/node-v6.9.1-x64.msi
  InstallerSha256: 148AA14CE1491B2CDC47230C90E862E48D1AF32BAF5CC415B29593B6113EA1CF
  ProductCode: '{672B5547-D20B-4D19-9BFD-B93C32BC77DA}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v6.9.1/node-v6.9.1-x86.msi
  InstallerSha256: 314EAF8B5B9E08A835CB5C005EA5F4299B9E9E4D8C97277C1617E511382C15DC
  ProductCode: '{CA6817E2-FC84-4443-A2AE-FC244047E898}'
ManifestType: installer
ManifestVersion: 1.6.0
