# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v4.9.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2018-03-28
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 4.9.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v4.9.0/node-v4.9.0-x86.msi
  InstallerSha256: BE4A46A7E464C58FBDF70F2C9F01FE0D80652F9180194B9CF716691673C5533E
  ProductCode: '{09ADD9D1-0CC4-44DF-9238-601F7831A2CF}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v4.9.0/node-v4.9.0-x64.msi
  InstallerSha256: 6E360CD2F18EBDF70FEE3ADCE67DC84F7EF5D8AFFA9C15B193C50578DDA2585A
  ProductCode: '{2DA78A16-5A5B-4964-9324-7C88ECBF07AF}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v4.9.0/node-v4.9.0-x86.msi
  InstallerSha256: BE4A46A7E464C58FBDF70F2C9F01FE0D80652F9180194B9CF716691673C5533E
  ProductCode: '{09ADD9D1-0CC4-44DF-9238-601F7831A2CF}'
ManifestType: installer
ManifestVersion: 1.6.0
