# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v18.15.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2023-03-05
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 18.15.0
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v18.15.0/node-v18.15.0-x86.msi
  InstallerSha256: F7A2096BF8C34DB99251E9CD9CE8EA4A7369BE4E9F57DAAA13B0F32C98DE94B6
  ProductCode: '{767359F7-2B5F-4D4E-B22A-7CE210BCE249}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v18.15.0/node-v18.15.0-x64.msi
  InstallerSha256: 36DE8D8FECD0920175ED6E61266934F3469888990F0CC54238E50437490515D5
  ProductCode: '{A4D82090-DD12-42C0-92F1-B5E2A134534C}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v18.15.0/node-v18.15.0-x86.msi
  InstallerSha256: F7A2096BF8C34DB99251E9CD9CE8EA4A7369BE4E9F57DAAA13B0F32C98DE94B6
  ProductCode: '{767359F7-2B5F-4D4E-B22A-7CE210BCE249}'
ManifestType: installer
ManifestVersion: 1.6.0
