# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 8.9.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2017-10-31
AppsAndFeaturesEntries:
- DisplayName: Node.js
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v8.9.0/node-v8.9.0-x86.msi
  InstallerSha256: 6B33268464EBBD60C6C8B271CBBBE4F52D87EDDE97DF5B165C1BCC1339D70045
  ProductCode: '{E6DF0261-6A56-4495-9DCC-3C1C91F4985C}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v8.9.0/node-v8.9.0-x64.msi
  InstallerSha256: CD37FF1FB455F7E6E6FE566CFFCEA06BBDE392501FD7B5BE5EC4174B762AF523
  ProductCode: '{B7F6FEC2-3415-45CA-8E1A-9C7C00E02DDC}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v8.9.0/node-v8.9.0-x86.msi
  InstallerSha256: 6B33268464EBBD60C6C8B271CBBBE4F52D87EDDE97DF5B165C1BCC1339D70045
  ProductCode: '{E6DF0261-6A56-4495-9DCC-3C1C91F4985C}'
ManifestType: installer
ManifestVersion: 1.6.0
