# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: v4.8.2
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2017-04-04
AppsAndFeaturesEntries:
- DisplayName: Node.js
  DisplayVersion: 4.8.2
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v4.8.2/node-v4.8.2-x86.msi
  InstallerSha256: 0DB29F887A7ABF3B246979A1016E8DC96F1D96B0652E04018313D1C3694CE989
  ProductCode: '{3AC59C1A-48BD-45AC-BA9E-FC390554AFE7}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v4.8.2/node-v4.8.2-x64.msi
  InstallerSha256: F7A14975CDCF4EB76727559A38C4CC26807F34133A751CD11EBC71C7A31D4EDA
  ProductCode: '{D2D953D4-3ED6-4ABE-93ED-A4F9F8125CAB}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v4.8.2/node-v4.8.2-x86.msi
  InstallerSha256: 0DB29F887A7ABF3B246979A1016E8DC96F1D96B0652E04018313D1C3694CE989
  ProductCode: '{3AC59C1A-48BD-45AC-BA9E-FC390554AFE7}'
ManifestType: installer
ManifestVersion: 1.6.0
