# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 12.14.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2019-12-17
AppsAndFeaturesEntries:
- DisplayName: Node.js
  UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://nodejs.org/dist/v12.14.0/node-v12.14.0-x86.msi
  InstallerSha256: 6C0E75BE48A2410749B58FD7482DD96A689940290F5D7A624F00CBAD0B901DF8
  ProductCode: '{B2690020-FBBB-4D28-B67A-FF7198404893}'
- Architecture: x64
  InstallerUrl: https://nodejs.org/dist/v12.14.0/node-v12.14.0-x64.msi
  InstallerSha256: BD0636856980C1FA855F1D517DCBD288A5619536286E4B1E452E19230355F7D9
  ProductCode: '{59DCC95C-1D0A-4BAB-AECB-8EE928BC6782}'
- Architecture: arm64
  InstallerUrl: https://nodejs.org/dist/v12.14.0/node-v12.14.0-x64.msi
  InstallerSha256: BD0636856980C1FA855F1D517DCBD288A5619536286E4B1E452E19230355F7D9
  ProductCode: '{59DCC95C-1D0A-4BAB-AECB-8EE928BC6782}'
ManifestType: installer
ManifestVersion: 1.6.0
