# Created with AutoPublish using komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: 7zip.7zip
PackageVersion: '24.06'
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- 7z
FileExtensions:
- 7z
- ar
- arj
- bzip2
- cab
- chm
- cpio
- cramfs
- dmg
- ext
- fat
- gpt
- gzip
- hfs
- ihex
- iso
- lzh
- lzma
- mbr
- msi
- nsis
- ntfs
- qcow2
- rar
- rpm
- squashfs
- tar
- udf
- uefi
- vdi
- vhd
- vmdk
- wim
- xar
- xz
- z
- zip
ReleaseDate: 2024-05-26
Installers:
- Architecture: x86
  InstallerUrl: https://7-zip.org/a/7z2406.exe
  InstallerSha256: 1EA62E6B152E4B7DBADF45289E04BF4EA7431C7928A9B3C6BA5E4C06FE368085
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerUrl: https://7-zip.org/a/7z2406-x64.exe
  InstallerSha256: 6220BBE6C26D87FC343E0FFA4E20CCFAFECA7DAB2742E41963C40B56FB884807
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerUrl: https://7-zip.org/a/7z2406-arm64.exe
  InstallerSha256: 43AC4903AC5BA7219C665637E71917C6A2C2F8E515344E1EE04C263B8F5C934D
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
- InstallerLocale: en-US
  Architecture: x86
  InstallerUrl: https://7-zip.org/a/7z2406.exe
  InstallerSha256: 1EA62E6B152E4B7DBADF45289E04BF4EA7431C7928A9B3C6BA5E4C06FE368085
  ElevationRequirement: elevatesSelf
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://7-zip.org/a/7z2406.exe
  InstallerSha256: 1EA62E6B152E4B7DBADF45289E04BF4EA7431C7928A9B3C6BA5E4C06FE368085
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.6.0
